# This is a basic workflow for integrating appdome-api-python with your github project
# File location should be under .github/workflows/
name: Appdome Android Fuse Build And Sign
description: Use basic flow for Appdome users for build and sign android vanilla applications as a part of your ci/cd workflow activity
branding:
  icon: 'bluetooth'
  color: 'blue'
# Controls when the workflow will run
runs:
  using: "composite"
  steps:
    - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
        with:
          path: main
    - name: Cloning appdome-api-python github repository
        uses: actions/checkout@master
        with:
          repository: Appdome/appdome-api-python
          ref: refs/heads/main
          path: appdome
    - name: Run dependencies installation
        run: |
            sudo apt update 
            sudo apt install python3-pip
            sudo pip3 install -r appdome/requirements.txt
        shell: bash
