# This is a basic workflow for integrating appdome-api-python with your github project
# File location should be under .github/workflows/
name: Appdome Android Fuse Build And Sign
description: Use basic flow for Appdome users for build and sign android vanilla applications as a part of your ci/cd workflow activity
branding:
  icon: 'bluetooth'
  color: 'blue'

inputs:
  Android_vanilla_file:
    description: 'APK file'
    # Default value if no value is explicitly provided
    default: ''
    # Input has to be provided for the workflow to run
    required: true
  Fusion_set_id:
    description: "Android fusion set id"
    default: ''
    required: true
  sign_otions:
    type: choice
    description: Android Sign Options
    options: 
    - Appdome Signing
    - Private Signing
    - Auto-Dev Private Signing
    required: true
  Keystore_file:
    description: 'Keystore file'
    default: ''
    required: false
  keystore_password:
    description: 'keystore password'
    default: ''
    required: false
  keystore_alias:
    description: 'keystore alias'
    default: ''
    required: false
  key_pass:
    description: 'keystore key password'
    default: ''
    required: false
  signing_fingerprint:
    description: 'signing sha1 fingerprint'
    default: ''
    required: false
  google_play_signing:
    description: 'Google Play App Signing program'
    type: boolean
    default: false
    required: false
  sign_overrids:
    description: 'Download link for json file with sign overrides'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Cloning appdome-api-python github repository
      uses: actions/checkout@master
      with:
        repository: Appdome/appdome-api-python
        ref: refs/heads/main
        path: appdome
    - name: My first step
      run: mkdir files | mkdir output
      shell: bash
    - name: My first step
      run: sudo apt update | sudo apt install python3-pip | sudo pip3 install -r appdome/requirements.txt
      shell: bash   
    - name: Cloning actions
      uses: actions/checkout@master
      with:
        repository: nirappdome/appdome_actions
        ref: refs/heads/main
        path: actions
    - name: permissions
      run: chmod +x ./actions/actions/download.sh
      shell: bash
    - name: Download files
      run: ./actions/actions/download.sh ${{github.event.inputs.keystore_file}} ${{github.event.inputs.sign_overrids}} ${{github.event.inputs.android_vanilla_file}}
      shell: bash
    - name: explore
      run: ls -lR
      shell: bash

