on:
#  release:
#    types:
#      - prereleased
  workflow_dispatch:

jobs:
  perpare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Replace RELEASE_TAG_PLACEHOLDER in pipeline.yml
      run: |
        sed -i "s/RELEASE_TAG_PLACEHOLDER/${{  github.ref_name }}/g" .github/workflows/pipeline.yml
        cat .github/workflows/pipeline.yml
  launch:
    needs: prepare
    uses: ".github/workflows/pipeline.yml"
    secrets: inherit
#    - name: Trigger pipeline.yml workflow
#      run: gh workflow run .github/workflows/pipeline.yml -R $GITHUB_REPOSITORY
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}